### ISSUE TITLE
No longer getting token

### ISSUE THREAD

**Issue by Hunanbean-Collective** [delebash/unreal_vault_organizer#7]
As of ~09/10/2023 it no longer seems to be able to get the token from the launcher.
Beyond that, you'd have to look into it yourself as i have no further information other than i have had this all working previously. I think the latest Launcher update changed things

Thank you for the cool tool

**Comment by G012481632** [comment]
Same over here, doesn't trust it ... ... now back to using 'the vault' ...

**Comment by delebash** [comment]
I just updated it with a fix, I think, it worked for me.  The problem is with the ssl certs.  You need to remove and re-add.   Here are the instructions from my discord channel.  


 It looks like there is a problem with ssl certs that was causing the app not to work.  I just updated the app with a Remove SSL certs button.  You will also need to delete the folder C:\Users\yourusername\ .mitmproxy.  Then try to install the certs again by clicking on the install certs button, then try getting the token.  This fixed the problem for me.  But as I mentioned to some other users I will not be working on this until we see what the new Unreal Market Place called Fab looks like.  It is set to be released this year.  Get the new release here https://github.com/delebash/unreal_vault_organizer/releases/tag/v1.4.52 or let it autoupdate if you have the exe

**Comment by G012481632** [comment]
Hi Daniel,

Thanks for responding !

I already had the latest version with the extra button. Tried it again, but
on my system my antivirus goes bezurk. I allowed the connections but still
get the same 'not trusted' notification.

I will wait on the new Fab to see how that fits our needs. Thanks again !

Cheers,
Geert

Op wo 27 sep 2023 om 18:38 schreef Daniel Elebash ***@***.***

**Comment by kferr** [comment]
I suspect this issue is tied to accounts that have auth token enabled as part of MFA for sign in. I was unable to get the app to get the right token because it would prompt me for my 60 second code for MFA. And if I logged in first and then tried the proxy solution, it just made it so it said the connection wasn't working. So doesn't look like MFA enabled accounts can pull this information.

**Comment by Hunanbean-Collective** [comment]
All i can say is that previously, shortly before my initial reporting of the issue, things were working, and i use 2FA

**Comment by delebash** [comment]
I am not sure why it isn't working.  It did stop working for me but once I removed and re-added the ssl cert it worked for me.  Try going to Internet Options > Content > Certificates > Trusted Root Certificates and delete mitmproxy.  Then re-add it using the Add ssl cert on the app.  See if that works.

**Comment by MatteoZorro** [comment]
I think I found the problem: it is not the program but the installer.
Yesterday I installed it and in the last window there was the option: "Run Unreal Vault Organizer". I did it, I followed the instruction and it didn't work.
Then today I tried it again and it worked perfectly. 
I think the problem is this: the installer doesn't run Unreal Vault Organizer as admin, so it cannot do the job.

**Comment by delebash** [comment]
Yes it does need to run as administrator, but it should do this by default.  Whenever I launch the program, it always asks for permission which sets it to run in admin mode.  Maybe different security settings in windows affect this.  Good find.

**Comment by MatteoZorro** [comment]
Whenever you double-click it, yes does. It is the first time after the installation, when it is automatically launched by the install program, that it doesn't get right permissions.
This is why I said that the thing with a problem is not the program itself, but the installation wizard.
Thank you for this very useful program :-)

**Comment by delebash** [comment]
Check the new release that works with FAB.  Also, there is new authentication method that does not require the sniffer component.  https://github.com/delebash/unreal_vault_organizer_tauri/releases/tag/uvo-v1.0.0
